### ISSUE TITLE
Fatal error running install.sh

### ISSUE THREAD

**Issue by Clara81221** [MusiKid/acpi_ec#16]
```
$ sudo bash install.sh
fatal: not a git repository (or any of the parent directories): .git
```

MSI Creator Z16P // Kali Linux

**Comment by feelingwalnut** [comment]
Sudo ./install.sh

?

**Comment by Clara81221** [comment]
No luck. Same error. The file is there too, I checked.

**Comment by feelingwalnut** [comment]
hmm, I believe all I did was extract it all to a folder from the 1.0.4 source release and ran the script.
on debian.

been a while.

**Comment by Clara81221** [comment]
Yea it seems like it _should_ work but I'm not sure why it's not

**Comment by RizzoV** [comment]
The installation script as is would require the .git directory to be bundled into the zip, which is not.

Replace line 36 in install.sh as following for a temporary workaround

```diff
- VERSION=$(git describe --tags --abbrev=0)
+ VERSION="1.0.4"
```

**Comment by Clara81221** [comment]
Installation worked, thank you
