### ISSUE TITLE
dkms Error during running make command

### ISSUE THREAD

**Issue by CiSJiK** [MusiKid/acpi_ec#2]
Hello.
When I run this script dkms error causes during on running make command. It said the struct called file_operations is not found.
So I've imported the kernel source it doesn't change the result.
May different kernel version make to fail?
Here is my operating system information.
`Kernel: 5.8.0-43-generic
OS: Ubuntu 20.04 LTS (Focal)
Secure Boot State: Fully Enabled(mokutil violation-validated and standard mode on BIOS)
`

**Comment by saidsay-so** [comment]
Can you try with the commit that I just pushed? It should work now.

**Comment by CiSJiK** [comment]
I tried re-clone this repository and ran that. But It seems to be broken.
I saw that VERSION variable was 1.0.1 but now it choose the result of `git describe --tags --abbrev=0`
When I ran that, I got fatal error: Nothing to describe.

**Comment by CiSJiK** [comment]
Okay. I replaced the variable, VERSION. It is set the value as 1.0.1 and it works fine.
I will try it on my other laptop. And I will tell you the result of others. Thanks once again.

**Comment by CiSJiK** [comment]
I installed by changing the VERSION value as 1.0.1 and It installed. But nbfc can't access to /dev/ec. What should I have to do?

**Comment by MusiKid** [comment]
Sorry for the version, I forgot yo push

**Comment by saidsay-so** [comment]
Sorry for the version, I forgot to push the tag 😅. And for NBFC, did you use my fork or pull it directly from the main repository? Because the commit still isn't merged (I'm going to remove the instructions from the wiki since they're misleading).

**Comment by CiSJiK** [comment]
I used hirschmann's repository. Let me try your fork instead.

EDIT: It doesn't work anyway :(

**Comment by saidsay-so** [comment]
Weird...
Maybe try to remove `ECSysLinux.dll` and `ECLinux.dll`.

**Comment by CiSJiK** [comment]
StagWare.Plugins.ECLinux.dll and StagWare.Plugins.ECSysLinux.dll removed and I ran `nbfc.exe start` it prompted could not load a plugin implements StagWare.FanControl.Plugins.IEmbeddedController.

**Comment by saidsay-so** [comment]
Do you have ECModuleLinux.dll in the same folder than the two others?

**Comment by CiSJiK** [comment]
No it is not. If you are talking about all of nbfc file in Release directory, those dll files are in Plugins directory.

**Comment by CiSJiK** [comment]
Also I got warning message during running build.sh. 
`The project configuration for project 'StagWare.Plugins.ECModuleLinux' corresponding to the solution configuration 'ReleaseLinux|Any CPU' was not found.`
Do it cause this issue?

**Comment by saidsay-so** [comment]
Yes it seems to be the issue. I will take a look at it ASAP

**Comment by saidsay-so** [comment]
It seems that it is unable to build the plugin because we have to add some parameters during the build (the architecture maybe?). I'll look which one should work.

**Comment by CiSJiK** [comment]
Thanks a lot. Hopes to see the best result :)

**Comment by saidsay-so** [comment]
Can you try to rebase and rebuild NBFC? I added the configuration for Linux and it seems to build it correctly (at least on my computer).

**Comment by CiSJiK** [comment]
It doesn't work. I'm still getting warning message I commented.
Here is the warning message from build.sh.

~/Downloads/nbfc/NoteBookFanControl.sln:  warning : Don't know how to handle GlobalSection ExtensibilityGlobals, Ignoring.

~/Downloads/nbfc/NoteBookFanControl.sln (Build) ->
(Build target) -> ~/Downloads/nbfc/NoteBookFanControl.sln:  warning : The project configuration for project 'StagWare.Plugins.ECModuleLinux' corresponding to the solution configuration 'ReleaseLinux|Any CPU' was not found.

**Comment by CiSJiK** [comment]
Can this message be caused by the type of operating system? I compiled that in Ubuntu 20.04 LTS. How about running build in Windows?

**Comment by CiSJiK** [comment]
Well, there is some problem with my laptop. Let me try with some another laptops to check it work or not.
Thanks once again.
