### ISSUE TITLE
dkms incorrect syntax

### ISSUE THREAD

**Issue by dumprop** [MusiKid/acpi_ec#3]
```fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
Generating a RSA private key
....++++
.........................................................................++++
writing new private key to '/root/mok.priv'
-----
The generated key is going to be imported into the secure keystore.
The following passphrase is only required once, during the following reboot.
Please press RETURN to go on.
input password: 
input password again: 

Please reboot your computer now to complete the enrollment of your new MOK.
This is going to look somewhat similar to https://sourceware.org/systemtap/wiki/SecureBoot
Error! Arguments <module> and <module-version> are not specified.
Usage: add <module>/<module-version> or
       add -m <module>/<module-version> or
       add -m <module> -v <module-version>
Error! Arguments <module> and <module-version> are not specified.
Usage: add <module>/<module-version> or
       add -m <module>/<module-version> or
       add -m <module> -v <module-version>
Error! Arguments <module> and <module-version> are not specified.
Usage: add <module>/<module-version> or
       add -m <module>/<module-version> or
       add -m <module> -v <module-version>
```
fedora 35, acpi_ec-1.0.2
Downloaded via git clone and there no such issue

**Comment by saidsay-so** [comment]
I tried to run it on my computer (Arch Linux) and it works flawlessly.
I will try to run it on a Fedora VM. Can you give me your version of DKMS please?

**Comment by dumprop** [comment]
> I tried to run it on my computer (Arch Linux) and it works flawlessly. I will try to run it on a Fedora VM. Can you give me your version of DKMS please?

dkms-2.8.6
but seems that problem only in release version, not git clone

**Comment by saidsay-so** [comment]
Did you download the source code from an archive when you talk about the "release version"? Because then the problem is that the script picks the latest tag, while the archive content is not a git repository.

**Comment by dumprop** [comment]
> Did you download the source code from an archive when you talk about the "release version"? Because then the problem is that the script picks the latest tag, while the archive content is not a git repository.

Yes
Currenly all seems well via git clone
