### ISSUE TITLE
How to install on new kernel

### ISSUE THREAD

**Issue by dumprop** [MusiKid/acpi_ec#5]
Before I had kernel 5.14.16, currently I have kernel 5.14.17
Any fan controller doesn't work:
```
modprobe: FATAL: Module ec_sys not found in directory /lib/modules/5.14.17-301.fc35.x86_64
Could not load `ec_sys' kernel module
```
When I try to install acpi_ec on new kernel again:
```
sudo ./install.sh 
acpi_ec v1.0.2 is already installed
```
But in fact it installed only on kernel 5.14.16 ....
```
Module acpi_ec-v1.0.2 for kernel 5.14.16-301.fc35.x86_64 (x86_64).
Before uninstall, this module version was ACTIVE on this kernel.

acpi_ec.ko.xz:
 - Uninstallation
   - Deleting from: /lib/modules/5.14.16-301.fc35.x86_64/extra/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.

depmod....
Module acpi_ec-v1.0.2 for kernel 5.14.16-301.fc35.x86_64 (x86_64).
This module version was INACTIVE for this kernel.
depmod....
Deleting module acpi_ec-v1.0.2 completely from the DKMS tree.
Uninstalled acpi_ec v1.0.2
[user@fedora acpi_ec]$ sudo ./install.sh 
WARNING: Secure Boot is not enabled!
Creating symlink /var/lib/dkms/acpi_ec/v1.0.2/source -> /usr/src/acpi_ec-v1.0.2

Kernel preparation unnecessary for this kernel. Skipping...

Building module:
cleaning build area...
make -j8 KERNELRELEASE=5.14.17-301.fc35.x86_64 -C /lib/modules/5.14.17-301.fc35.x86_64/build M=/var/lib/dkms/acpi_ec/v1.0.2/build/src modules...
cleaning build area...

acpi_ec.ko.xz:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.14.17-301.fc35.x86_64/extra/

depmod....
```

**Comment by saidsay-so** [comment]
DKMS should rebuild the module when a new kernel version is installed ~~(and it seems to be the case according to your logs)~~.

**Comment by dumprop** [comment]
> DKMS should rebuild the module when a new kernel version is installed (and it seems to be the case according to your logs). 

According my logs there no rebuild :)
In the end I had to uninstall and install again

**Comment by dumprop** [comment]
On opensuse tumbleweed there no such problems

**Comment by saidsay-so** [comment]
It seems to be a Fedora-specific problem then. Did you try to `modprobe` the module?

**Comment by dumprop** [comment]
> It seems to be a Fedora-specific problem then. Did you try to `modprobe` the module?

No, currently I use opensuse and all works well 🙂

**Comment by saidsay-so** [comment]
I will close the issue since it seems to be a problem with Fedora rather than the module.

**Comment by dumprop** [comment]
> I will close the issue since it seems to be a problem with Fedora rather than the module.

but it will be cool to figure out this problem 
at least find solutions
